### ISSUE TITLE
Test the Stock YOLOv9 Model on All Objects in the Updated SUAS Rules

### ISSUE THREAD

**Issue by OrangePear13** [MissouriMRR/SUAS-2025#33]
# Test the Stock YOLOv9 Model on All Objects in the Updated SUAS Rules

## Problem

The SUAS rules have been updated to have less ambiguity in the types of possible objects that need to be detected. A team member has noticed that the types of objects are all ones that the pre-trained YOLOv9 model should be able to classify. This needs to be verified.

## Solution

Run an unmodified YOLOv9 model on sample images of SUAS objects found from the internet and report on the effectiveness of the model in accurate identification and classification

## Additional Information

Technically, the rules have also specified that we do not need the ability necessarily differentiate between different possible valid objects, so correct classification is less important, as long as the classification is one of the valid objects.

**Comment by graylogan** [comment]
I ran the tests and recorded the results. They can be found in the report in the following repository:
https://github.com/graylogan/Stock-YOLOv9-Test

**Comment by graylogan** [comment]
close
